"use client";
import React, { useState, useEffect, useMemo } from "react";
import { z } from "zod";
import { useForm, Controller } from "react-hook-form";
import CustomSelect from "@/components/common/CustomSelect";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  User,
  MapPin,
  Phone,
  Building,
  Loader2,
  Save
} from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";

// Updated imports
import { authRequest } from "@/lib/axiosCreate";
import { showToast } from "@/lib/features/toast/toastSlice";
import { useDispatch } from "react-redux";

const beneficiaryTypes = ["Individual", "Business", "Government", "Non-Profit"];
const bankAccountTypes = ["SAVINGS", "CURRENT", "FIXED_DEPOSIT", "RECURRING_DEPOSIT"];
const payeeTypes = ["DOMESTIC", "INTERNATIONAL"];

// Validation regex patterns
const swiftRegex = /^[A-Za-z0-9]{8}([A-Za-z0-9]{3})?$/;
const ifscRegex = /^[A-Z]{4}0[A-Z0-9]{6}$/;
const ibanRegex = /^[A-Z]{2}[0-9]{2}[A-Z0-9]{1,30}$/;
const accountNumberRegex = /^[0-9]{9,18}$/;
const sortCodeRegex = /^[0-9]{6}$/;

// Schema for create mode
const createPayeeSchema = (payeeType) => {
  const baseSchema = z.object({
    ben_code: z.string().min(1, "Beneficiary code is required"),
    ben_name: z.string().min(1, "Beneficiary name is required"),
    add1: z.string().min(1, "Address 1 is required"),
    add2: z.string().optional().or(z.literal("")),
    city: z.string().min(1, "City is required"),
    state: z.string().min(1, "State is required"),
    zipcode: z.string().min(1, "Zipcode is required"),
    contact: z.string().min(1, "Contact is required"),
    email: z.string().email("Enter a valid email"),
    payee_type: z.enum(payeeTypes, { errorMap: () => ({ message: "Payee type is required" }) }),
    acc_no: z.string().min(1, payeeType === "INTERNATIONAL" ? "IBAN is required" : "Account number is required"),
    bank_name: z.string().min(1, "Bank name is required"),
    branch: z.string().min(1, "Branch is required"),
    bank_account_type: z.enum(bankAccountTypes, {
      errorMap: () => ({ message: "Bank account type is required" }),
    }),
  });

  if (payeeType === "DOMESTIC") {
    return baseSchema.extend({
      acc_no: z.string()
        .min(1, "Account number is required")
        .regex(accountNumberRegex, "Account number must be 9-18 digits"),
      ifsc: z.string()
        .min(1, "IFSC Code is required for Domestic payee")
        .regex(ifscRegex, "IFSC code must be 11 characters in format: ABCD0123456"),
    });
  } else {
    return baseSchema.extend({
      acc_no: z.string()
        .min(1, "IBAN is required for International payee")
        .regex(ibanRegex, "IBAN must be in valid format (e.g., GB82WEST12345698765432)"),
      ifsc: z.string().optional(),
      swift_code: z.string()
        .min(1, "SWIFT Code is required for International payee")
        .regex(swiftRegex, "SWIFT Code must be 8 or 11 alphanumeric characters"),
      sort_code: z.string()
        .min(1, "Sort Code is required for International payee")
        .regex(sortCodeRegex, "Sort Code must be 6 digits"),
    });
  }
};

export default function AddNewPayeePage() {
  const router = useRouter();
  const dispatch = useDispatch();
  const searchParams = useSearchParams();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [autoGeneratedCode, setAutoGeneratedCode] = useState("");
  const [currentPayeeType, setCurrentPayeeType] = useState("DOMESTIC");
  const [referralCode, setReferralCode] = useState("");

  // Get referral code from URL query parameter
  useEffect(() => {
    const referralCodeFromUrl = searchParams.get('referral_code');
    console.log("Referral code from URL:", referralCodeFromUrl);

    if (referralCodeFromUrl) {
      setReferralCode(referralCodeFromUrl);
    } else {
      // Fallback: Try to extract from path as well
      const pathSegments = window.location.pathname.split('/');
      const codeIndex = pathSegments.findIndex(segment => segment === 'add-payee') + 1;

      if (codeIndex > 0 && pathSegments[codeIndex]) {
        setReferralCode(pathSegments[codeIndex]);
      }
      // Note: Removed toast here to avoid spamming if not found immediately, or could keep it.
    }
  }, [searchParams, dispatch]);

  // Create dynamic schema based on current payee type
  const payeeSchema = useMemo(() =>
    createPayeeSchema(currentPayeeType),
    [currentPayeeType]
  );
  const {
    register,
    handleSubmit,
    reset,
    watch,
    setValue,
    clearErrors,
    control,
    formState: { errors },
  } = useForm({
    resolver: zodResolver(payeeSchema),
    defaultValues: {
      ben_code: "",
      ben_name: "",
      add1: "",
      add2: "",
      city: "",
      state: "",
      zipcode: "",
      contact: "",
      email: "",
      payee_type: "DOMESTIC",
      acc_no: "",
      ifsc: "",
      swift_code: "",
      sort_code: "",
      bank_name: "",
      branch: "",
      bank_account_type: "",
    },
  });

  const watchedPayeeType = watch("payee_type");
  const isInternational = watchedPayeeType === "INTERNATIONAL";

  // Dynamic label for Account No / IBAN
  const accountLabel = useMemo(() => (isInternational ? "IBAN" : "Account No"), [isInternational]);

  // Generate unique beneficiary code with letters and numbers (capital letters)
  const generateBeneficiaryCode = () => {
    const letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const numbers = '0123456789';

    // Generate 3 random capital letters
    let letterPart = '';
    for (let i = 0; i < 3; i++) {
      letterPart += letters.charAt(Math.floor(Math.random() * letters.length));
    }

    // Generate 4 random numbers
    let numberPart = '';
    for (let i = 0; i < 4; i++) {
      numberPart += numbers.charAt(Math.floor(Math.random() * numbers.length));
    }

    // Generate 2 more random capital letters
    let suffixPart = '';
    for (let i = 0; i < 2; i++) {
      suffixPart += letters.charAt(Math.floor(Math.random() * letters.length));
    }

    const newCode = `BEN${letterPart}${numberPart}${suffixPart}`;
    return newCode;
  };

  // Auto-generate code when component mounts
  useEffect(() => {
    const newCode = generateBeneficiaryCode();
    setAutoGeneratedCode(newCode);
    setValue("ben_code", newCode);
  }, [setValue]);

  // Update schema when payee type changes
  useEffect(() => {
    if (watchedPayeeType !== currentPayeeType) {
      setCurrentPayeeType(watchedPayeeType);
    }
  }, [watchedPayeeType, currentPayeeType]);

  // Clear and validate conditional fields when switching payee types
  useEffect(() => {
    if (isInternational) {
      // Switching to INTERNATIONAL - clear IFSC
      setValue("ifsc", "");
      clearErrors("ifsc");
    } else {
      // Switching to DOMESTIC - clear SWIFT & Sort Code
      setValue("swift_code", "");
      setValue("sort_code", "");
      clearErrors(["swift_code", "sort_code"]);
    }
  }, [isInternational, setValue, clearErrors]);

  // Function to regenerate beneficiary code
  const regenerateBeneficiaryCode = () => {
    const newCode = generateBeneficiaryCode();
    setAutoGeneratedCode(newCode);
    setValue("ben_code", newCode);
    clearErrors("ben_code");
  };

  const onSubmit = async (data) => {
    if (!referralCode) {
      dispatch(
        showToast({
          message: "Referral code is missing from URL",
          type: "error",
        })
      );
      return;
    }

    setIsSubmitting(true);

    try {
      const apiPayeeType = data.payee_type.toUpperCase();

      // Prepare the payload according to your API structure
      const payeeData = {
        ben_code: data.ben_code,
        ben_name: data.ben_name,
        add1: data.add1,
        add2: data.add2 || "",
        city: data.city,
        state: data.state,
        zipcode: data.zipcode,
        contact: data.contact,
        email: data.email,
        payee_type: apiPayeeType,
        acc_no: data.acc_no,
        bank_name: data.bank_name,
        branch: data.branch,
        bank_account_type: data.bank_account_type,
      };

      // Add appropriate fields based on payee type
      if (apiPayeeType === "DOMESTIC") {
        payeeData.ifsc = data.ifsc;
        // Remove international fields if they exist
        delete payeeData.swift_code;
        delete payeeData.sort_code;
        delete payeeData.iban;
      } else {
        // INTERNATIONAL payee
        payeeData.swift_code = data.swift_code;
        payeeData.sort_code = data.sort_code;
        payeeData.iban = data.acc_no; // Map acc_no to iban for international
        // Remove domestic fields
        delete payeeData.ifsc;
      }

      console.log("Submitting payee data:", payeeData);
      console.log("Using referral code:", referralCode);

      // Make API call with referral code in URL
      const response = await authRequest.post(`/api/payor/payees/referral/${referralCode}/`, payeeData);

      console.log("API Response:", response.data);

      reset();

      dispatch(
        showToast({
          message: "Payee added successfully!",
          type: "success",
        })
      );



    } catch (error) {
      console.error('Error adding payee:', error);
      let errorMessage = "Failed to add payee";

      if (error.response?.data) {
        const apiErrors = error.response.data;
        console.log("API Error Response:", apiErrors);

        // Handle duplicate ben_code error
        if (apiErrors.ben_code && apiErrors.ben_code.includes("already exists")) {
          regenerateBeneficiaryCode();
          errorMessage = "Duplicate beneficiary code detected. A new code has been generated. Please try again.";
        }
        // Handle payee_type validation error
        else if (apiErrors.non_field_errors && apiErrors.non_field_errors.includes("Invalid payee_type")) {
          errorMessage = "Invalid payee type. Please select either DOMESTIC or INTERNATIONAL.";
        }
        // Handle referral code errors
        else if (apiErrors.detail && apiErrors.detail.includes("referral")) {
          errorMessage = "Invalid or expired referral code. Please check the URL.";
        }
        else if (typeof apiErrors === 'object') {
          errorMessage = Object.entries(apiErrors)
            .map(([field, messages]) => `${field}: ${Array.isArray(messages) ? messages.join(', ') : messages}`)
            .join('\n');
        } else {
          errorMessage = apiErrors;
        }
      } else if (error.message) {
        errorMessage = error.message;
      }

      dispatch(
        showToast({
          message: errorMessage,
          type: "error",
        })
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleReset = () => {
    const newCode = generateBeneficiaryCode();
    setAutoGeneratedCode(newCode);
    reset({
      ben_code: newCode,
      ben_name: "",
      add1: "",
      add2: "",
      city: "",
      state: "",
      zipcode: "",
      contact: "",
      email: "",
      payee_type: "DOMESTIC",
      acc_no: "",
      ifsc: "",
      swift_code: "",
      sort_code: "",
      bank_name: "",
      branch: "",
      bank_account_type: "",
    });
  };

  // Reusable Tailwind classes for inputs and labels to ensure consistency
  const inputClass = (hasError) => `
    flex h-10 w-full rounded-md border bg-white px-3 py-2 text-sm 
    file:border-0 file:bg-transparent file:text-sm file:font-medium 
    placeholder:text-gray-500 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#FFCA00] 
    ${hasError ? "border-red-500 focus-visible:ring-red-500" : "border-gray-200"}
  `;

  const labelClass = "text-sm font-medium leading-none text-gray-700 peer-disabled:cursor-not-allowed peer-disabled:opacity-70";

  return (
    <div className="min-h-screen w-full bg-slate-50 py-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">

        {/* Header Section */}
        <div className="mb-8">
          <div className="flex items-center gap-4 mb-4">
            <h1 className="text-3xl font-bold text-gray-900">Enter Your Details</h1>
          </div>
        </div>

        {/* Main Form */}
        <div className="bg-white rounded-2xl shadow-lg border border-gray-100 overflow-hidden">
          <form onSubmit={handleSubmit(onSubmit)} className="p-6 space-y-8">

            {/* Basic Information Section */}
            <section className="space-y-6">
              <div className="flex items-center gap-3 pb-3 border-b border-gray-100">
                <div className="p-2 rounded-lg bg-[#FFCA00]/10 hover:bg-[#d9ac00]">
                  <User className="h-5 w-5 text-[#FFCA00]" />
                </div>
                <h2 className="text-lg font-semibold text-gray-900">Basic Information</h2>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Beneficiary Code */}
                <div className="space-y-2">
                  <label htmlFor="ben_code" className={labelClass}>
                    Beneficiary Code
                  </label>
                  <div className="flex gap-3">
                    <input
                      id="ben_code"
                      readOnly
                      className={`${inputClass(errors.ben_code)} bg-gray-50 font-mono uppercase cursor-not-allowed text-gray-500`}
                      {...register("ben_code")}
                    />
                  </div>
                  {errors.ben_code && (
                    <p className="text-sm text-red-600 font-medium">
                      {errors.ben_code.message}
                    </p>
                  )}
                </div>

                {/* Beneficiary Name */}
                <div className="space-y-2">
                  <label htmlFor="ben_name" className={labelClass}>
                    Beneficiary Name <span className="text-red-500">*</span>
                  </label>
                  <input
                    id="ben_name"
                    placeholder="Enter beneficiary full name"
                    className={inputClass(errors.ben_name)}
                    {...register("ben_name")}
                  />
                  {errors.ben_name && (
                    <p className="text-sm text-red-600 font-medium">
                      {errors.ben_name.message}
                    </p>
                  )}
                </div>
              </div>
            </section>

            {/* Address Information Section */}
            <section className="space-y-6">
              <div className="flex items-center gap-3 pb-3 border-b border-gray-100">
                <div className="p-2 rounded-lg bg-[#FFCA00]/10 hover:bg-[#d9ac00]">
                  <MapPin className="h-5 w-5 text-[#FFCA00]" />
                </div>
                <h2 className="text-lg font-semibold text-gray-900">Address Information</h2>
              </div>

              <div className="grid grid-cols-1 gap-6">
                {/* Address Line 1 */}
                <div className="space-y-2">
                  <label htmlFor="add1" className={labelClass}>
                    Address Line 1 <span className="text-red-500">*</span>
                  </label>
                  <input
                    id="add1"
                    placeholder="Street address, P.O. box, company name"
                    className={inputClass(errors.add1)}
                    {...register("add1")}
                  />
                  {errors.add1 && (
                    <p className="text-sm text-red-600 font-medium">
                      {errors.add1.message}
                    </p>
                  )}
                </div>

                {/* Address Line 2 */}
                <div className="space-y-2">
                  <label htmlFor="add2" className={labelClass}>Address Line 2 (Optional)</label>
                  <input
                    id="add2"
                    placeholder="Apartment, suite, unit, building, floor, etc."
                    className={inputClass(false)}
                    {...register("add2")}
                  />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  {/* City */}
                  <div className="space-y-2">
                    <label htmlFor="city" className={labelClass}>
                      City <span className="text-red-500">*</span>
                    </label>
                    <input
                      id="city"
                      placeholder="City"
                      className={inputClass(errors.city)}
                      {...register("city")}
                    />
                    {errors.city && (
                      <p className="text-sm text-red-600 font-medium">
                        {errors.city.message}
                      </p>
                    )}
                  </div>

                  {/* State */}
                  <div className="space-y-2">
                    <label htmlFor="state" className={labelClass}>
                      State <span className="text-red-500">*</span>
                    </label>
                    <input
                      id="state"
                      placeholder="State/Province/Region"
                      className={inputClass(errors.state)}
                      {...register("state")}
                    />
                    {errors.state && (
                      <p className="text-sm text-red-600 font-medium">
                        {errors.state.message}
                      </p>
                    )}
                  </div>

                  {/* Zipcode */}
                  <div className="space-y-2">
                    <label htmlFor="zipcode" className={labelClass}>
                      Zipcode <span className="text-red-500">*</span>
                    </label>
                    <input
                      id="zipcode"
                      placeholder="ZIP/Postal code"
                      className={inputClass(errors.zipcode)}
                      {...register("zipcode")}
                    />
                    {errors.zipcode && (
                      <p className="text-sm text-red-600 font-medium">
                        {errors.zipcode.message}
                      </p>
                    )}
                  </div>
                </div>
              </div>
            </section>

            {/* Contact Information Section */}
            <section className="space-y-6">
              <div className="flex items-center gap-3 pb-3 border-b border-gray-100">
                <div className="p-2 rounded-lg bg-[#FFCA00]/10 hover:bg-[#d9ac00]">
                  <Phone className="h-5 w-5 text-[#FFCA00]" />
                </div>
                <h2 className="text-lg font-semibold text-gray-900">Contact Information</h2>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Contact Number */}
                <div className="space-y-2">
                  <label htmlFor="contact" className={labelClass}>
                    Contact Number <span className="text-red-500">*</span>
                  </label>
                  <input
                    id="contact"
                    placeholder="Phone number"
                    className={inputClass(errors.contact)}
                    {...register("contact")}
                  />
                  {errors.contact && (
                    <p className="text-sm text-red-600 font-medium">
                      {errors.contact.message}
                    </p>
                  )}
                </div>

                {/* Email */}
                <div className="space-y-2">
                  <label htmlFor="email" className={labelClass}>
                    Email Address <span className="text-red-500">*</span>
                  </label>
                  <input
                    id="email"
                    type="email"
                    placeholder="Email address"
                    className={inputClass(errors.email)}
                    {...register("email")}
                  />
                  {errors.email && (
                    <p className="text-sm text-red-600 font-medium">
                      {errors.email.message}
                    </p>
                  )}
                </div>
              </div>
            </section>

            {/* Payee Type Section */}
            <section className="space-y-6">
              <div className="flex items-center gap-3 pb-3 border-b border-gray-100">
                <div className="p-2 rounded-lg bg-[#FFCA00]/10 hover:bg-[#d9ac00]">
                  <Building className="h-5 w-5 text-[#FFCA00]" />
                </div>
                <h2 className="text-lg font-semibold text-gray-900">Payee Type</h2>
              </div>

              <div className="max-w-md space-y-2">
                <label className={labelClass}>
                  Payee Type <span className="text-red-500">*</span>
                </label>
                <Controller
                  name="payee_type"
                  control={control}
                  render={({ field }) => (
                    <CustomSelect
                      {...field}
                      options={payeeTypes.map(t => ({ value: t, label: t }))}
                      error={errors.payee_type}
                    />
                  )}
                />
                {errors.payee_type && (
                  <p className="text-sm text-red-600 font-medium mt-2">
                    {errors.payee_type.message}
                  </p>
                )}
              </div>
            </section>

            {/* Banking Information Section */}
            <section className="space-y-6">
              <div className="flex items-center gap-3 pb-3 border-b border-gray-100">
                <div className="p-2 rounded-lg bg-[#FFCA00]/10 hover:bg-[#d9ac00]">
                  <Building className="h-5 w-5 text-[#FFCA00]" />
                </div>
                <h2 className="text-lg font-semibold text-gray-900">Banking Information</h2>
              </div>

              {/* Account/IBAN and IFSC (conditional) */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <label htmlFor="acc_no" className={labelClass}>
                    {accountLabel} <span className="text-red-500">*</span>
                  </label>
                  <input
                    id="acc_no"
                    placeholder={
                      isInternational
                        ? "Enter IBAN (e.g., GB82WEST12345698765432)"
                        : "Enter account number (9-18 digits)"
                    }
                    className={inputClass(errors.acc_no)}
                    {...register("acc_no")}
                  />
                  {errors.acc_no && (
                    <p className="text-sm text-red-600 font-medium">
                      {errors.acc_no.message}
                    </p>
                  )}
                  {!errors.acc_no && isInternational && (
                    <p className="text-xs text-gray-500">
                      Format: Country code + Check digits + Basic Bank Account Number
                    </p>
                  )}
                </div>

                {/* Show IFSC only for DOMESTIC */}
                {!isInternational && (
                  <div className="space-y-2">
                    <label htmlFor="ifsc" className={labelClass}>
                      IFSC Code <span className="text-red-500">*</span>
                    </label>
                    <input
                      id="ifsc"
                      maxLength={11}
                      placeholder="Enter IFSC code (e.g., SBIN0123456)"
                      className={`${inputClass(errors.ifsc)} uppercase`}
                      {...register("ifsc")}
                    />
                    {errors.ifsc && (
                      <p className="text-sm text-red-600 font-medium">
                        {errors.ifsc.message}
                      </p>
                    )}
                    {!errors.ifsc && (
                      <p className="text-xs text-gray-500">
                        11 characters: 4 letters + 0 + 6 alphanumeric
                      </p>
                    )}
                  </div>
                )}
              </div>

              {/* INTERNATIONAL-only fields */}
              {isInternational && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-2">
                    <label htmlFor="swift_code" className={labelClass}>
                      SWIFT Code <span className="text-red-500">*</span>
                    </label>
                    <input
                      id="swift_code"
                      maxLength={11}
                      placeholder="Enter SWIFT code (8 or 11 characters)"
                      className={`${inputClass(errors.swift_code)} uppercase`}
                      {...register("swift_code")}
                    />
                    {errors.swift_code && (
                      <p className="text-sm text-red-600 font-medium">
                        {errors.swift_code.message}
                      </p>
                    )}
                    {!errors.swift_code && (
                      <p className="text-xs text-gray-500">
                        8 or 11 alphanumeric characters (e.g., BOFAUS3NXXX)
                      </p>
                    )}
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="sort_code" className={labelClass}>
                      Sort Code <span className="text-red-500">*</span>
                    </label>
                    <input
                      id="sort_code"
                      maxLength={6}
                      placeholder="Enter Sort Code (6 digits)"
                      className={inputClass(errors.sort_code)}
                      {...register("sort_code")}
                    />
                    {errors.sort_code && (
                      <p className="text-sm text-red-600 font-medium">
                        {errors.sort_code.message}
                      </p>
                    )}
                    {!errors.sort_code && (
                      <p className="text-xs text-gray-500">
                        6 digits (e.g., 123456)
                      </p>
                    )}
                  </div>
                </div>
              )}

              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="space-y-2">
                  <label htmlFor="bank_name" className={labelClass}>
                    Bank Name <span className="text-red-500">*</span>
                  </label>
                  <input
                    id="bank_name"
                    placeholder="Bank name"
                    className={inputClass(errors.bank_name)}
                    {...register("bank_name")}
                  />
                  {errors.bank_name && (
                    <p className="text-sm text-red-600 font-medium">
                      {errors.bank_name.message}
                    </p>
                  )}
                </div>

                <div className="space-y-2">
                  <label htmlFor="branch" className={labelClass}>
                    Branch <span className="text-red-500">*</span>
                  </label>
                  <input
                    id="branch"
                    placeholder="Branch name"
                    className={inputClass(errors.branch)}
                    {...register("branch")}
                  />
                  {errors.branch && (
                    <p className="text-sm text-red-600 font-medium">
                      {errors.branch.message}
                    </p>
                  )}
                </div>

                <div className="space-y-2">
                  <label className={labelClass}>
                    Bank Account Type <span className="text-red-500">*</span>
                  </label>
                  <Controller
                    name="bank_account_type"
                    control={control}
                    render={({ field }) => (
                      <CustomSelect
                        {...field}
                        options={bankAccountTypes.map(t => ({ value: t, label: t.replace('_', ' ') }))}
                        placeholder="Select account type"
                        error={errors.bank_account_type}
                        isDisabled={isSubmitting}
                      />
                    )}
                  />
                  {errors.bank_account_type && (
                    <p className="text-sm text-red-600 font-medium">
                      {errors.bank_account_type.message}
                    </p>
                  )}
                </div>
              </div>
            </section>

            {/* Action Buttons */}
            <div className="flex flex-col sm:flex-row gap-4 pt-8 border-t border-gray-100">
              <button
                type="button"
                onClick={handleReset}
                disabled={isSubmitting}
                className="w-full sm:w-auto px-8 py-3 rounded-lg border border-gray-300 text-gray-700 font-medium hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-gray-200 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                Reset Form
              </button>

              <button
                type="submit"
                disabled={isSubmitting || !referralCode}
                className="w-full sm:w-auto flex items-center justify-center gap-2 bg-[#FFCA00] hover:bg-[#d9ac00] text-black font-medium py-3 px-8 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#FFCA00]/50 disabled:bg-gray-300 disabled:text-gray-500 disabled:cursor-not-allowed"
              >
                {isSubmitting ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Uploading...
                  </>
                ) : (
                  <>
                    <Save className="h-4 w-4" />
                    Upload Data
                  </>
                )}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}